#!/bin/bash

#----------------------------------------------------
#Özet: ...
#Yazar: @neynefes
#Kaynak:....
#----------------------------------------------------

   1) exit 0;;
esac
clear; tput bold
tput setaf 208
echo -e "\n${message[3]} \n"
tput setaf 219
cat /tmp/cpuinfo
while read line; do
if [[ $(echo $line|grep '^[0-9]'|awk '{print $1}'|cut -d. -f1) -ge 30 ]]; then
echo $line >>/tmp/cpuwarning
fi
done <<<$(cat /tmp/cpuinfo)
tput setaf 208
if [[ -e /tmp/cpuwarning ]] && [[ -e /usr/share/sounds/gnome/default/alerts/Xylo.ogg ]]; then
VLM=`amixer sget 'Master'|grep '[0-9]%'|cut -d[ -f2|cut -d% -f1|head -1`
amixer sset 'Master' 90% &>/dev/null
sleep 1
canberra-gtk-play --file="/usr/share/sounds/gnome/default/alerts/Xylo.ogg" &
echo -e "\n ${message[4]}\n "
amixer sset 'Master' $VLM% &>/dev/null
tput setaf 226
cat /tmp/cpuwarning
elif [[ -e /tmp/cpuwarning ]]; then
echo -e "\n ${message[4]}\n "
tput setaf 226
cat /tmp/cpuwarning
fi
tput sgr0
